sudo: required
services:
  - docker

before_install:
  - docker build -t yanivohayon8/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yanivohayon8/react-test npm test

after_success:
  - docker build -t yanivohayon8/multi-client ./client
  - docker build -t yanivohayon8/multi-nginx ./nginx
  - docker build -t yanivohayon8/multi-server ./server
  - docker build -t yanivohayon8/multi-worker ./worker
  # Login in to docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  # PUSh to docker hub
  - docker push yanivohayon8/multi-client
  - docker push yanivohayon8/multi-nginx
  - docker push yanivohayon8/multi-server
  - docker push yanivohayon8/multi-worker
  
